/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as PurchaseSuccessRouteImport } from './routes/purchase/success'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AccountAccountViewRouteImport } from './routes/account/$accountView'
import { Route as DashboardPatientsIndexRouteImport } from './routes/dashboard/patients/index'
import { Route as DashboardAiBlogIndexRouteImport } from './routes/dashboard/ai-blog/index'
import { Route as DashboardAiAssistantIndexRouteImport } from './routes/dashboard/ai-assistant/index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiRssXmlRouteImport } from './routes/api/rss.xml'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseSuccessRoute = PurchaseSuccessRouteImport.update({
  id: '/purchase/success',
  path: '/purchase/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/$accountView',
  path: '/$accountView',
  getParentRoute: () => AccountRouteRoute,
} as any)
const DashboardPatientsIndexRoute = DashboardPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAiBlogIndexRoute = DashboardAiBlogIndexRouteImport.update({
  id: '/ai-blog/',
  path: '/ai-blog/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAiAssistantIndexRoute =
  DashboardAiAssistantIndexRouteImport.update({
    id: '/ai-assistant/',
    path: '/ai-assistant/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRssXmlRoute = ApiRssXmlRouteImport.update({
  id: '/api/rss/xml',
  path: '/api/rss/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/purchase/success': typeof PurchaseSuccessRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rss/xml': typeof ApiRssXmlRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/ai-assistant/': typeof DashboardAiAssistantIndexRoute
  '/dashboard/ai-blog/': typeof DashboardAiBlogIndexRoute
  '/dashboard/patients/': typeof DashboardPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/purchase/success': typeof PurchaseSuccessRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rss/xml': typeof ApiRssXmlRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantIndexRoute
  '/dashboard/ai-blog': typeof DashboardAiBlogIndexRoute
  '/dashboard/patients': typeof DashboardPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/purchase/success': typeof PurchaseSuccessRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rss/xml': typeof ApiRssXmlRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/ai-assistant/': typeof DashboardAiAssistantIndexRoute
  '/dashboard/ai-blog/': typeof DashboardAiBlogIndexRoute
  '/dashboard/patients/': typeof DashboardPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/purchase/success'
    | '/blog/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/rss/xml'
    | '/api/stripe/webhook'
    | '/dashboard/ai-assistant/'
    | '/dashboard/ai-blog/'
    | '/dashboard/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/purchase/success'
    | '/blog'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/rss/xml'
    | '/api/stripe/webhook'
    | '/dashboard/ai-assistant'
    | '/dashboard/ai-blog'
    | '/dashboard/patients'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/purchase/success'
    | '/blog/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/rss/xml'
    | '/api/stripe/webhook'
    | '/dashboard/ai-assistant/'
    | '/dashboard/ai-blog/'
    | '/dashboard/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PurchaseSuccessRoute: typeof PurchaseSuccessRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRssXmlRoute: typeof ApiRssXmlRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/success': {
      id: '/purchase/success'
      path: '/purchase/success'
      fullPath: '/purchase/success'
      preLoaderRoute: typeof PurchaseSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/dashboard/patients/': {
      id: '/dashboard/patients/'
      path: '/patients'
      fullPath: '/dashboard/patients/'
      preLoaderRoute: typeof DashboardPatientsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ai-blog/': {
      id: '/dashboard/ai-blog/'
      path: '/ai-blog'
      fullPath: '/dashboard/ai-blog/'
      preLoaderRoute: typeof DashboardAiBlogIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ai-assistant/': {
      id: '/dashboard/ai-assistant/'
      path: '/ai-assistant'
      fullPath: '/dashboard/ai-assistant/'
      preLoaderRoute: typeof DashboardAiAssistantIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rss/xml': {
      id: '/api/rss/xml'
      path: '/api/rss/xml'
      fullPath: '/api/rss/xml'
      preLoaderRoute: typeof ApiRssXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteRouteChildren {
  AccountAccountViewRoute: typeof AccountAccountViewRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountAccountViewRoute: AccountAccountViewRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAiAssistantIndexRoute: typeof DashboardAiAssistantIndexRoute
  DashboardAiBlogIndexRoute: typeof DashboardAiBlogIndexRoute
  DashboardPatientsIndexRoute: typeof DashboardPatientsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAiAssistantIndexRoute: DashboardAiAssistantIndexRoute,
  DashboardAiBlogIndexRoute: DashboardAiBlogIndexRoute,
  DashboardPatientsIndexRoute: DashboardPatientsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  BlogSlugRoute: BlogSlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PurchaseSuccessRoute: PurchaseSuccessRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRssXmlRoute: ApiRssXmlRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
